services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: nestle_backend_image:latest
    ports:
      - "1221:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app/src
      - ENVIRONMENT=development
    container_name: nestle_backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped